version: '2'
services:
    firstimpressions-app:
        image: firstimpressions
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://firstimpressions-mysql:3306/firstimpressions?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://firstimpressions-elasticsearch:9200
        ports:
            - 8080:8080
    firstimpressions-mysql:
        extends:
            file: mysql.yml
            service: firstimpressions-mysql
    firstimpressions-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: firstimpressions-elasticsearch
